from terminal_case33.data.case33bw_raw import load_raw_case33bw
from terminal_case33.estimation.sensitivity import estimate_reduced_sensitivity
from terminal_case33.models.lin_distflow import build_reduced_sensitivity_matrices
from terminal_case33.models.timeseries import simulate_terminal_load_timeseries
from terminal_case33.scenario.terminalize import terminalize_case33


def test_noiseless_small_signal_ac_recovers_local_sensitivity():
    net = terminalize_case33(load_raw_case33bw(), seed=4)
    terminals = net.buses[net.buses["bus_type"].eq("observed_terminal")]["bus_id"].astype(int).tolist()
    R, X = build_reduced_sensitivity_matrices(net, terminals)
    sim = simulate_terminal_load_timeseries(
        net,
        760,
        60,
        "step_probe",
        load_scale=0.1,
        pf_mode="time_varying_pf",
        noise_config={},
        v0_config={"sigma": 0.0},
        seed=4,
    )
    est = estimate_reduced_sensitivity(
        sim["V_terminal_meas"],
        sim["P_terminal_meas"],
        sim["Q_terminal_meas"],
        method="ridge",
        alpha=1e-10,
        include_root_voltage_mode=False,
    )
    # Measurements are now generated by nonlinear AC power flow, so the
    # reduced LinDistFlow matrix is recovered as a local small-signal model.
    assert abs(est.R_hat.to_numpy() - R).mean() < 3e-3
    assert abs(est.X_hat.to_numpy() - X).mean() < 3e-3


def test_correlated_profiles_have_worse_condition_number():
    net = terminalize_case33(load_raw_case33bw(), seed=5)
    step = simulate_terminal_load_timeseries(net, 300, 60, "step_probe", v0_config={"sigma": 0.0}, seed=5)
    corr = simulate_terminal_load_timeseries(net, 300, 60, "correlated_residential", v0_config={"sigma": 0.0}, seed=5)
    est_step = estimate_reduced_sensitivity(step["V_terminal_meas"], step["P_terminal_meas"], step["Q_terminal_meas"], include_root_voltage_mode=False)
    est_corr = estimate_reduced_sensitivity(corr["V_terminal_meas"], corr["P_terminal_meas"], corr["Q_terminal_meas"], include_root_voltage_mode=False)
    assert est_corr.condition_number > est_step.condition_number


def test_root_voltage_mode_improves_common_mode_fit():
    net = terminalize_case33(load_raw_case33bw(), seed=6)
    sim = simulate_terminal_load_timeseries(net, 300, 60, "step_probe", v0_config={"sigma": 0.004}, seed=6)
    no_root = estimate_reduced_sensitivity(sim["V_terminal_meas"], sim["P_terminal_meas"], sim["Q_terminal_meas"], include_root_voltage_mode=False)
    with_root = estimate_reduced_sensitivity(
        sim["V_terminal_meas"],
        sim["P_terminal_meas"],
        sim["Q_terminal_meas"],
        include_root_voltage_mode=True,
        root_voltage=sim["V_root_true"],
    )
    assert with_root.r2_score >= no_root.r2_score
