"""Dimensionless raw LinDistFlow observations, generated by shared root paths."""
import numpy as np
from .model import Data, Tree


def small_tree(ambiguous=False):
    edges = (("root", "h"), ("h", "g"), ("g", "a"), ("g", "b"), ("h", "c"))
    candidates = ("h", "g", "a", "b", "c")
    if ambiguous:
        edges += (("h", "u"), ("u", "v"))
        candidates += ("u", "v")
    return Tree(edges, ("a", "b", "c"), candidates)


def true_parameters(tree):
    extra = len(tree.edges) - 5
    return (np.array([.09, .075, .12, .1, .11] + [.055] * extra),
            np.array([.07, .05, .08, .065, .06] + [.035] * extra))


def simulate(*, seed=13, samples=12, kind="hidden", noise=False, loss_bias=0.,
             ambiguous=False, strength=1., voltage_scale=.002, balance_scale=.03):
    tree = small_tree(ambiguous)
    rng = np.random.default_rng(seed)
    p = rng.uniform(.2, 1.2, (samples, 3))
    q = rng.uniform(.03, .5, (samples, 3))
    amplitude = strength * rng.uniform(.35, .9, samples)
    locations = np.full(samples, -1, int)
    if kind == "hidden":
        locations[:] = 1
    elif kind == "terminal":
        locations[:] = 2
    elif kind == "switching":
        locations[:] = np.resize([-1, 1, 2, 4, 0, 3], samples)
    elif kind == "spur":
        locations[:] = tree.candidates.index("v")
    elif kind != "normal":
        raise ValueError(kind)
    amplitude[locations < 0] = 0
    r, x = true_parameters(tree)
    parent = {child: (node, edge) for edge, (node, child) in enumerate(tree.edges)}

    def path(node):
        result = set()
        while node in parent:
            node, edge = parent[node]
            result.add(edge)
        return result

    paths = {node: path(node) for node in tree.observed + tree.candidates}
    y = np.zeros_like(p)
    kappa = .25
    for t in range(samples):
        for i, observed in enumerate(tree.observed):
            for j, source in enumerate(tree.observed):
                shared = list(paths[observed] & paths[source])
                y[t, i] += r[shared].sum() * p[t, j] + x[shared].sum() * q[t, j]
            if locations[t] >= 0:
                shared = list(paths[observed] & paths[tree.candidates[locations[t]]])
                y[t, i] += amplitude[t] * (r[shared].sum() + kappa * x[shared].sum())
    loss = .025 * p.sum(axis=1)
    master = p.sum(axis=1) + loss + amplitude
    if noise:
        y += rng.laplace(0, voltage_scale, y.shape)
        master += rng.laplace(0, balance_scale, samples)
    estimated_loss = loss - loss_bias
    signed_balance = master - p.sum(axis=1) - estimated_loss
    fixed_amplitude = np.maximum(signed_balance, 0)
    fixed_amplitude[np.abs(fixed_amplitude) < 1e-12] = 0
    data = Data(p, q, y, signed_balance, fixed_amplitude, kappa * fixed_amplitude,
                voltage_scale, balance_scale)
    truth = {"r": r, "x": x, "locations": locations, "amplitude": amplitude,
             "master": master, "technical_loss": loss, "estimated_loss": estimated_loss,
             "kappa": kappa}
    return tree, data, truth
