"""Backtracking recursive grouping used by Pengwah (2022) and Flynn (2023)."""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations

import networkx as nx
import numpy as np


WeightedEdge = tuple[int, int, float]


@dataclass(frozen=True)
class GroupingDecision:
    """One parent-child or sibling decision in a candidate construction."""

    relation: str
    left: int
    right: int
    score: float
    t_parent: float
    t_noise: float


@dataclass(frozen=True)
class GroupingCandidate:
    """One complete candidate generated by recursive grouping/backtracking."""

    edges: tuple[WeightedEdge, ...]
    decisions: tuple[GroupingDecision, ...]
    construction_score: float
    distance_stress: float


@dataclass(frozen=True)
class EnhancedGroupingResult:
    """Ranked candidate trees from enhanced recursive grouping."""

    nodes: tuple[int, ...]
    root: int | None
    candidates: tuple[GroupingCandidate, ...]
    selected_index: int
    truncated: bool

    @property
    def best(self) -> GroupingCandidate:
        """Return the minimum-stress candidate."""

        return self.candidates[self.selected_index]


@dataclass
class _State:
    active: list[int]
    values: dict[tuple[int, int], float]
    edges: list[WeightedEdge]
    decisions: list[GroupingDecision]
    next_hidden: int
    score: float


@dataclass(frozen=True)
class _Option:
    relation: str
    left: int
    right: int
    score: float
    t_parent: float
    t_noise: float
    parent: int | None = None
    child: int | None = None
    left_limb: float | None = None
    right_limb: float | None = None


def _key(left: int, right: int) -> tuple[int, int]:
    return (left, right) if left < right else (right, left)


def _get(values: dict[tuple[int, int], float], left: int, right: int) -> float:
    return 0.0 if left == right else values[_key(left, right)]


def _distance_stress(edges: list[WeightedEdge], labels: list[int], target: np.ndarray) -> float:
    graph = nx.Graph()
    graph.add_weighted_edges_from(edges)
    if not nx.is_tree(graph) or not set(labels).issubset(graph.nodes):
        return float("inf")
    predicted = np.asarray(
        [[nx.shortest_path_length(graph, left, right, weight="weight") for right in labels] for left in labels]
    )
    return float(np.linalg.norm(predicted - target, ord="fro") / max(np.linalg.norm(target, ord="fro"), 1e-15))


def _relation_options(
    state: _State,
    observed_leaves: set[int],
    root: int | None,
    epsilon: float,
) -> tuple[_Option | None, _Option | None]:
    parent_options: list[_Option] = []
    sibling_options: list[_Option] = []
    for left, right in combinations(state.active, 2):
        others = [node for node in state.active if node not in {left, right}]
        separation = _get(state.values, left, right)
        if others:
            phi = np.asarray([_get(state.values, left, node) - _get(state.values, right, node) for node in others])
            mean_phi = float(np.mean(phi))
            t_noise = float(np.max(phi) - np.min(phi))
        else:
            mean_phi = 0.0
            t_noise = 0.0
        t_parent = abs(separation - abs(mean_phi))
        parent, child = (right, left) if mean_phi >= 0.0 else (left, right)
        parent_valid = parent not in observed_leaves and child != root
        if root is not None and parent == root:
            parent_valid = True
        if parent_valid:
            parent_options.append(
                _Option("parent_child", left, right, t_parent, t_parent, t_noise, parent=parent, child=child)
            )

        left_limb = 0.5 * (separation + mean_phi)
        right_limb = separation - left_limb
        sibling_valid = root not in {left, right} and min(left_limb, right_limb) > epsilon
        if sibling_valid and all(
            0.5
            * (
                _get(state.values, left, node)
                - left_limb
                + _get(state.values, right, node)
                - right_limb
            )
            >= -epsilon
            for node in others
        ):
            sibling_options.append(
                _Option(
                    "siblings",
                    left,
                    right,
                    t_noise,
                    t_parent,
                    t_noise,
                    left_limb=max(0.0, left_limb),
                    right_limb=max(0.0, right_limb),
                )
            )
    best_parent = min(parent_options, key=lambda item: (item.score, _key(item.left, item.right))) if parent_options else None
    best_sibling = min(sibling_options, key=lambda item: (item.score, _key(item.left, item.right))) if sibling_options else None
    return best_parent, best_sibling


def _apply_option(state: _State, option: _Option) -> _State:
    active = list(state.active)
    values = dict(state.values)
    edges = list(state.edges)
    decisions = list(state.decisions)
    decisions.append(
        GroupingDecision(
            option.relation,
            option.left,
            option.right,
            option.score,
            option.t_parent,
            option.t_noise,
        )
    )
    next_hidden = state.next_hidden
    if option.relation == "parent_child":
        assert option.parent is not None and option.child is not None
        edges.append((option.parent, option.child, _get(values, option.parent, option.child)))
        active.remove(option.child)
    else:
        assert option.left_limb is not None and option.right_limb is not None
        hidden = next_hidden
        next_hidden -= 1
        edges.extend(
            [
                (hidden, option.left, option.left_limb),
                (hidden, option.right, option.right_limb),
            ]
        )
        remaining = [node for node in active if node not in {option.left, option.right}]
        for node in remaining:
            estimate = 0.5 * (
                _get(values, option.left, node)
                - option.left_limb
                + _get(values, option.right, node)
                - option.right_limb
            )
            values[_key(hidden, node)] = max(0.0, float(estimate))
        active = remaining + [hidden]
    return _State(active, values, edges, decisions, next_hidden, state.score + option.score)


def enhanced_recursive_grouping(
    distance_matrix: np.ndarray,
    nodes: list[int],
    observed_leaves: set[int] | None = None,
    root: int | None = None,
    epsilon: float = 1e-8,
    kappa: float = 10.0,
    max_candidates: int | None = None,
    enforce_physical_constraints: bool = True,
) -> EnhancedGroupingResult:
    """Generate candidate latent trees with Pengwah/Flynn backtracking.

    The relation tests are

    ``T_noise = max_k phi_ijk - min_k phi_ijk`` and
    ``T_parent = |d_ij - |mean_k phi_ijk||``.

    Ambiguous parent-child/sibling decisions are both explored when their
    score ratio lies in ``[1/kappa, kappa]``.  Flynn's physical constraints
    are enabled by default: two metered leaves cannot be parent and child,
    sibling limb lengths must be positive, and the supplied root cannot gain
    a parent.
    """

    labels = [int(node) for node in nodes]
    distance = np.asarray(distance_matrix, dtype=float)
    if distance.shape != (len(labels), len(labels)):
        raise ValueError("distance_matrix shape must match nodes")
    if epsilon < 0.0 or kappa < 1.0 or (max_candidates is not None and max_candidates < 1):
        raise ValueError("invalid epsilon, kappa, or max_candidates")
    distance = np.maximum(0.0, 0.5 * (distance + distance.T))
    np.fill_diagonal(distance, 0.0)
    leaves = set(labels if observed_leaves is None else observed_leaves)
    if not enforce_physical_constraints:
        leaves = set()
    values = {
        _key(left, right): float(distance[i, j])
        for i, left in enumerate(labels)
        for j, right in enumerate(labels)
        if i < j
    }
    next_hidden = min([-1, *(node for node in labels if node < 0)]) - 1
    stack = [_State(list(labels), values, [], [], next_hidden, 0.0)]
    complete: list[GroupingCandidate] = []
    truncated = False
    while stack and (max_candidates is None or len(complete) < max_candidates):
        state = stack.pop()
        if len(state.active) == 1:
            stress = _distance_stress(state.edges, labels, distance)
            complete.append(GroupingCandidate(tuple(state.edges), tuple(state.decisions), state.score, stress))
            continue
        if len(state.active) == 2:
            left, right = state.active
            final_edges = [*state.edges, (left, right, _get(state.values, left, right))]
            stress = _distance_stress(final_edges, labels, distance)
            complete.append(GroupingCandidate(tuple(final_edges), tuple(state.decisions), state.score, stress))
            continue
        parent_option, sibling_option = _relation_options(state, leaves, root, epsilon)
        available = [item for item in (parent_option, sibling_option) if item is not None]
        if not available:
            truncated = True
            continue
        available.sort(key=lambda item: (item.score, item.relation, _key(item.left, item.right)))
        selected = [available[0]]
        if len(available) == 2:
            low = max(min(available[0].score, available[1].score), 1e-15)
            high = max(available[0].score, available[1].score)
            if high / low <= kappa:
                selected.append(available[1])
        for option in reversed(selected):
            stack.append(_apply_option(state, option))
    if stack:
        truncated = True
    if not complete:
        raise RuntimeError("enhanced recursive grouping produced no feasible candidate")
    complete.sort(key=lambda item: (item.distance_stress, item.construction_score, len(item.edges)))
    return EnhancedGroupingResult(tuple(labels), root, tuple(complete), 0, truncated)
