mode: all_loads_to_new_terminal_leaves
service_impedance_mode: lv_cable_soumalas_style
service_length_m: 30.0
service_length_random_range_m: [28.0, 32.0]
T: 360
dt_seconds: 60
profile_mode: independent_residential
pf_mode: original_qp_ratio
noise_config:
  p_std: 0.0001
  q_std: 0.0001
  v_std: 0.0003
v0_config:
  sigma: 0.001
seed: 19
experiments:
  - soumalas_style_lv

